name: flutter_new_project_template_with_riverpod
description: "Flutter template to help devs start building apps faster than ever. It includes general usecases for project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.3.0
  flutter_riverpod: ^2.5.1

  flutter_annual_task:

    git:

      url: https://github.com/mehroze-zaidi/flutter_annual_task.git
      ref: master
  flutter_screenutil: ^5.9.3
  logger: ^2.4.0
  go_router: ^14.2.7
  flutter_scripts: ^0.0.2
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_logo/progress_path_logo.png"
  adaptive_icon_background: "#119D18"
  adaptive_icon_foreground: "assets/app_logo/progress_path_logo.png"

scripts:
  generate_icons: flutter pub run flutter_launcher_icons
  generate_files: dart run build_runner build --delete-conflicting-outputs
  watch_files: dart run build_runner watch --delete-conflicting-outputs
  watch: dart run build_runner build watch --delete-conflicting-outputs
  buildApk: flutter clean && flutter build apk
  buildAbb: flutter clean && flutter build appbundle
